In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [34]:
df = pd.DataFrame([[1,0,0,1, "mammals"],
                   [0,0,0,0, "non-mammals"],
                   [0,0,1,0, "non-mammals"],
                   [1,0,1,0, "mammals"],
                   [0,0,2,1, "non-mammals"],
                   [0,0,0,1, "non-mammals"],
                   [1,1,0,1, "mammals"],
                   [0,1,0,1, "non-mammals"],
                   [1,0,0,1, "mammals"],
                   [1,0,1,0, "non-mammals"],
                   [0,0,2,1, "non-mammals"],
                   [0,0,2,1, "non-mammals"],
                   [1,0,0,1, "mammals"],
                   [0,0,1,0, "non-mammals"],
                   [0,0,2,1, "non-mammals"],
                   [0,0,0,1, "non-mammals"],
                   [0,0,0,1, "mammal"],
                   [0,1,0,1, "non-mammals"],
                   [1,0,1,0, "mammals"],
                   [0,1,0,1, "non-mammals"]
                  ], columns = ['Give Birth', 'Can Fly', 'Live in Water', 'Have Legs', 'Class'])

In [35]:
df.head()

Give Birth  Can Fly  Live in Water  Have Legs        Class
0           1        0              0          1      mammals
1           0        0              0          0  non-mammals
2           0        0              1          0  non-mammals
3           1        0              1          0      mammals
4           0        0              2          1  non-mammals

In [36]:
cor = df.corr()
cor.style.background_gradient(cmap='coolwarm')

In [37]:
target = df.pop('Class')
df.head()

Give Birth  Can Fly  Live in Water  Have Legs
0           1        0              0          1
1           0        0              0          0
2           0        0              1          0
3           1        0              1          0
4           0        0              2          1

In [9]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [38]:
model = GaussianNB()
model.fit(df, target)

GaussianNB(priors=None, var_smoothing=1e-09)

## Solution using NB

In [39]:
input_data = pd.DataFrame([[1,0,2,1]])
predicted_data = model.predict(input_data)

print(predicted_data)

['mammals']


In [40]:
expected = target
predicted = model.predict(df)

In [41]:
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

      mammal       0.33      1.00      0.50         1
     mammals       0.86      1.00      0.92         6
 non-mammals       1.00      0.77      0.87        13

   micro avg       0.85      0.85      0.85        20
   macro avg       0.73      0.92      0.76        20
weighted avg       0.92      0.85      0.87        20

[[ 1  0  0]
 [ 0  6  0]
 [ 2  1 10]]
